# Bulls Analytics - Data Exploration

**Purpose:** Explore what data is available from the NBA API for our Bulls Instagram analytics project.

**Date:** January 2026  
**Phase:** 1 - Foundation

---

## What This Notebook Covers
1. Connecting to the NBA API
2. Finding the Bulls team data
3. Pulling game schedules
4. Getting player box scores (traditional + advanced stats)
5. Understanding what data we have to work with

---

In [29]:
# My first NBA data exploration
from nba_api.stats.static import teams

## Step 1: Setup & Team Lookup

First, we import the NBA API's static data to look up team information.

In [30]:
# Get all NBA teams
all_teams = teams.get_teams()
print(f"Found {len(all_teams)} teams")

Found 30 teams

In [31]:
# What does a team entry look like?
all_teams[0]

{'id': 1610612737,
 'full_name': 'Atlanta Hawks',
 'abbreviation': 'ATL',
 'nickname': 'Hawks',
 'city': 'Atlanta',
 'state': 'Georgia',
 'year_founded': 1949}

In [32]:
# Find the Chicago Bulls
bulls = [team for team in all_teams if team['full_name'] == 'Chicago Bulls'][0]
print(f"Team: {bulls['full_name']}")
print(f"Abbreviation: {bulls['abbreviation']}")
print(f"Team ID: {bulls['id']}")

Team: Chicago Bulls
Abbreviation: CHI
Team ID: 1610612741

In [33]:
# Import the endpoint to get game data
from nba_api.stats.endpoints import leaguegamefinder

# Get only regular season games
# The LeagueGameFinder has a season_type parameter
bulls_regular_season = leaguegamefinder.LeagueGameFinder(
    team_id_nullable=bulls['id'],
    season_nullable='2025-26',
    season_type_nullable='Regular Season'  # Filter to regular season only!
).get_data_frames()[0]

print(f"Regular season games: {len(bulls_regular_season)}")
bulls_games.head()  # Show first 5 games

Regular season games: 36

  SEASON_ID     TEAM_ID TEAM_ABBREVIATION  ... TOV  PF PLUS_MINUS
0     22025  1610612741               CHI  ...  11  13      -14.0
1     22025  1610612741               CHI  ...  11  16      -13.0
2     22025  1610612741               CHI  ...  12  15        7.0
3     22025  1610612741               CHI  ...   7  18       16.0
4     22025  1610612741               CHI  ...  16  17      -35.0

[5 rows x 28 columns]

## Step 2: Get Bulls Game Schedule

Now we fetch all Bulls regular season games using the `LeagueGameFinder` endpoint.

In [34]:
# Get the most recent game ID
# Games are sorted by date, so first row is most recent
latest_game_id = bulls_regular_season.iloc[0]['GAME_ID']
latest_game_date = bulls_regular_season.iloc[0]['GAME_DATE']
latest_matchup = bulls_regular_season.iloc[0]['MATCHUP']

print(f"Most recent game: {latest_matchup}")
print(f"Date: {latest_game_date}")
print(f"Game ID: {latest_game_id}")

Most recent game: CHI @ BOS
Date: 2026-01-05
Game ID: 0022500503

In [35]:
from nba_api.stats.endpoints import boxscoretraditionalv3

# Get detailed stats for that game
box_score = boxscoretraditionalv3.BoxScoreTraditionalV3(game_id=latest_game_id)

# The API returns multiple data frames - player stats is the first one
player_stats = box_score.player_stats.get_data_frame()

print(f"Players in this game: {len(player_stats)}")
player_stats.head(10)

Players in this game: 27

       gameId      teamId teamCity  ... foulsPersonal points plusMinusPoints
0  0022500503  1610612738   Boston  ...             2     14            12.0
1  0022500503  1610612738   Boston  ...             2      9             6.0
2  0022500503  1610612738   Boston  ...             1     13            11.0
3  0022500503  1610612738   Boston  ...             1     21            11.0
4  0022500503  1610612738   Boston  ...             1     10             0.0
5  0022500503  1610612738   Boston  ...             0      8             3.0
6  0022500503  1610612738   Boston  ...             1      5             5.0
7  0022500503  1610612738   Boston  ...             0     27            10.0
8  0022500503  1610612738   Boston  ...             1      5             7.0
9  0022500503  1610612738   Boston  ...             2      3             5.0

[10 rows x 34 columns]

In [37]:
# Filter to Bulls players only
# V3 uses 'teamId' (camelCase) instead of 'TEAM_ID'
bulls_players = player_stats[player_stats['teamId'] == bulls['id']]

# Create a full name column and select key stats
# V3 column names are different!
bulls_players = bulls_players.copy()
bulls_players['playerName'] = bulls_players['firstName'] + ' ' + bulls_players['familyName']

key_stats = bulls_players[['playerName', 'minutes', 'points', 'reboundsTotal', 'assists', 
                            'steals', 'blocks', 'fieldGoalsMade', 'fieldGoalsAttempted',
                            'threePointersMade', 'threePointersAttempted']]
key_stats.sort_values('points', ascending=False)

          playerName minutes  ...  threePointersMade  threePointersAttempted
16     Matas Buzelis   30:58  ...                  3                       4
17    Nikola Vučević   36:21  ...                  3                       5
21       Ayo Dosunmu   27:48  ...                  3                       7
19         Tre Jones   23:22  ...                  0                       1
18     Kevin Huerter   19:39  ...                  0                       4
25      Jevon Carter   11:46  ...                  2                       5
24   Julian Phillips   13:14  ...                  2                       4
15       Isaac Okoro   24:52  ...                  1                       7
20        Coby White   25:23  ...                  1                       5
26       Dalen Terry    4:55  ...                  1                       1
23  Patrick Williams   10:03  ...                  0                       2
22   Lachlan Olbrich   11:39  ...                  0                       1

[12 rows x 11 columns]

## Step 3: Get Player Box Score Data

For any specific game, we can get detailed player stats using the box score endpoints.

**Key Learning:** The NBA API deprecated V2 endpoints for the 2025-26 season. Use V3 endpoints instead (e.g., `boxscoretraditionalv3`).

In [38]:
# Let's see everything we already have
print("All stats from basic box score:")
for col in player_stats.columns:
    print(f"  - {col}")

All stats from basic box score:
  - gameId
  - teamId
  - teamCity
  - teamName
  - teamTricode
  - teamSlug
  - personId
  - firstName
  - familyName
  - nameI
  - playerSlug
  - position
  - comment
  - jerseyNum
  - minutes
  - fieldGoalsMade
  - fieldGoalsAttempted
  - fieldGoalsPercentage
  - threePointersMade
  - threePointersAttempted
  - threePointersPercentage
  - freeThrowsMade
  - freeThrowsAttempted
  - freeThrowsPercentage
  - reboundsOffensive
  - reboundsDefensive
  - reboundsTotal
  - assists
  - steals
  - blocks
  - turnovers
  - foulsPersonal
  - points
  - plusMinusPoints

In [39]:
from nba_api.stats.endpoints import boxscoreadvancedv3, boxscoremiscv3, boxscorescoringv3

# Advanced stats (offensive rating, usage rate, etc.)
advanced = boxscoreadvancedv3.BoxScoreAdvancedV3(game_id=latest_game_id)
advanced_stats = advanced.player_stats.get_data_frame()
print("ADVANCED STATS columns:")
print(advanced_stats.columns.tolist())

ADVANCED STATS columns:
['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug', 'personId', 'firstName', 'familyName', 'nameI', 'playerSlug', 'position', 'comment', 'jerseyNum', 'minutes', 'estimatedOffensiveRating', 'offensiveRating', 'estimatedDefensiveRating', 'defensiveRating', 'estimatedNetRating', 'netRating', 'assistPercentage', 'assistToTurnover', 'assistRatio', 'offensiveReboundPercentage', 'defensiveReboundPercentage', 'reboundPercentage', 'turnoverRatio', 'effectiveFieldGoalPercentage', 'trueShootingPercentage', 'usagePercentage', 'estimatedUsagePercentage', 'estimatedPace', 'pace', 'pacePer40', 'possessions', 'PIE']

In [40]:
# Miscellaneous stats
misc = boxscoremiscv3.BoxScoreMiscV3(game_id=latest_game_id)
misc_stats = misc.player_stats.get_data_frame()
print("\nMISC STATS columns:")
print(misc_stats.columns.tolist())

MISC STATS columns:
['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug', 'personId', 'firstName', 'familyName', 'nameI', 'playerSlug', 'position', 'comment', 'jerseyNum', 'minutes', 'pointsOffTurnovers', 'pointsSecondChance', 'pointsFastBreak', 'pointsPaint', 'oppPointsOffTurnovers', 'oppPointsSecondChance', 'oppPointsFastBreak', 'oppPointsPaint', 'blocks', 'blocksAgainst', 'foulsPersonal', 'foulsDrawn']

In [41]:
# Scoring breakdown
scoring = boxscorescoringv3.BoxScoreScoringV3(game_id=latest_game_id)
scoring_stats = scoring.player_stats.get_data_frame()
print("\nSCORING BREAKDOWN columns:")
print(scoring_stats.columns.tolist())

SCORING BREAKDOWN columns:
['gameId', 'teamId', 'teamCity', 'teamName', 'teamTricode', 'teamSlug', 'personId', 'firstName', 'familyName', 'nameI', 'playerSlug', 'position', 'comment', 'jerseyNum', 'minutes', 'percentageFieldGoalsAttempted2pt', 'percentageFieldGoalsAttempted3pt', 'percentagePoints2pt', 'percentagePointsMidrange2pt', 'percentagePoints3pt', 'percentagePointsFastBreak', 'percentagePointsFreeThrow', 'percentagePointsOffTurnovers', 'percentagePointsPaint', 'percentageAssisted2pt', 'percentageUnassisted2pt', 'percentageAssisted3pt', 'percentageUnassisted3pt', 'percentageAssistedFGM', 'percentageUnassistedFGM']

## Step 4: Explore Available Stats

The NBA API has multiple box score endpoints, each with different stats:

| Endpoint | What It Contains |
|----------|------------------|
| `boxscoretraditionalv3` | Basic stats (PTS, REB, AST, etc.) |
| `boxscoreadvancedv3` | Advanced metrics (Usage %, ORtg, DRtg, TS%) |
| `boxscoremiscv3` | Misc stats (Points in paint, fast break, etc.) |
| `boxscorescoringv3` | Scoring breakdown (% assisted, shot distribution) |

In [42]:
import pandas as pd

# Make pandas display all columns nicely
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# Merge the interesting stats together (they all have 'personId' in common)
bulls_traditional = player_stats[player_stats['teamId'] == bulls['id']].copy()
bulls_advanced = advanced_stats[advanced_stats['teamId'] == bulls['id']].copy()
bulls_misc = misc_stats[misc_stats['teamId'] == bulls['id']].copy()
bulls_scoring = scoring_stats[scoring_stats['teamId'] == bulls['id']].copy()

# Create player name
bulls_traditional['player'] = bulls_traditional['firstName'] + ' ' + bulls_traditional['familyName']

# Select the most interesting columns from each
combined = bulls_traditional[['player', 'minutes', 'points', 'reboundsTotal', 'assists', 
                               'steals', 'blocks', 'turnovers', 'plusMinusPoints',
                               'fieldGoalsMade', 'fieldGoalsAttempted', 'fieldGoalsPercentage',
                               'threePointersMade', 'threePointersAttempted']].copy()

# Add some advanced stats
combined['usageRate'] = bulls_advanced['usagePercentage'].values
combined['trueShootingPct'] = bulls_advanced['trueShootingPercentage'].values
combined['offRating'] = bulls_advanced['offensiveRating'].values
combined['defRating'] = bulls_advanced['defensiveRating'].values

# Add scoring breakdown
combined['pctPointsPaint'] = bulls_scoring['percentagePointsPaint'].values
combined['pctAssisted'] = bulls_scoring['percentageAssistedFGM'].values

# Sort by points and display
combined = combined.sort_values('points', ascending=False)
print(f"📊 BULLS vs CELTICS - {latest_game_date}")
print("=" * 80)
combined

📊 BULLS vs CELTICS - 2026-01-05
================================================================================

,player,minutes,points,reboundsTotal,assists,steals,blocks,turnovers,plusMinusPoints,fieldGoalsMade,fieldGoalsAttempted,fieldGoalsPercentage,threePointersMade,threePointersAttempted,usageRate,trueShootingPct,offRating,defRating,pctPointsPaint,pctAssisted
16,Matas Buzelis,30:58,26,3,2,0,1,2,-6.0,9,12,0.750,3,4,0.229,0.888,112.9,126.7,0.462,0.667
17,Nikola Vučević,36:21,15,15,7,1,0,2,-10.0,6,14,0.429,3,5,0.200,0.536,109.6,120.0,0.267,0.833
21,Ayo Dosunmu,27:48,15,3,5,0,1,0,-4.0,6,13,0.462,3,7,0.210,0.577,120.0,127.3,0.400,0.667
19,Tre Jones,23:22,10,5,4,0,0,1,-7.0,4,7,0.571,0,1,0.180,0.635,100.0,110.4,0.600,0.000
18,Kevin Huerter,19:39,8,3,0,0,1,1,-12.0,4,9,0.444,0,4,0.238,0.444,82.1,112.8,0.750,0.750
25,Jevon Carter,11:46,6,1,1,0,0,0,-1.0,2,6,0.333,2,5,0.250,0.500,117.4,121.7,0.000,1.000
24,Julian Phillips,13:14,6,2,0,1,0,0,-9.0,2,5,0.400,2,4,0.167,0.600,85.7,117.9,0.000,1.000
15,Isaac Okoro,24:52,5,3,1,0,1,1,-6.0,1,7,0.143,1,7,0.158,0.317,107.8,117.3,0.000,1.000
20,Coby White,25:23,5,6,3,0,0,4,-5.0,2,7,0.286,1,5,0.196,0.357,120.0,130.0,0.400,0.500
26,Dalen Terry,4:55,3,0,0,0,0,0,-1.0,1,1,1.000,1,1,0.091,1.500,120.0,130.0,0.000,1.000
23,Patrick Williams,10:03,2,2,0,0,0,0,-5.0,1,4,0.250,0,2,0.182,0.250,60.0,89.5,0.000,0.000
22,Lachlan Olbrich,11:39,0,2,2,0,0,0,-4.0,0,1,0.000,0,1,0.038,0.000,91.3,113.6,0.000,0.000